personality = "pragmatic"
model = "gpt-5.3-codex"
service_tier = "fast"
model_reasoning_effort = "medium"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
"gpt-5.1-codex-mini" = "gpt-5.4"

[features]
multi_agent = true

[projects."/Users/hank/workspace/mine/ai/ai-exp"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/dotfiles"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/ai/all-in-rag"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/petowns/petown-api"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/notebook"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/petowns/petown-data-tool"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/go-projects/washer"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/go-projects/markdown-preview"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/go-projects/video-downloader"]
trust_level = "trusted"

[projects."/Users/hank/workspace/mine/ai/aics"]
trust_level = "trusted"
